# Site settings
title: charles
email: kidccc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  lift is short,be happy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ichengchao.github.io" # the base hostname & protocol for your site
twitter_username: kobe
github_username:  ichengchao

# Build settings
markdown: kramdown
host: 0.0.0.0
