markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "feelinlee"

author: "feelinlee"
atom-baseurl: "http://feelinlee.github.io"
host: 0.0.0.0
navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

